#pragma kernel CSMain

RWTexture2D<float4> Result;

int2 Size;
int FocalLength;
float3 PlanetPos;
float PlanetRadius;
float3 CameraPos;
float3 CameraDir;
float3 SunDir;

int Octaves;
bool AbsoluteTerrain;
float StartFrequency;
float StartAmplitude;
float WarpStrength;
float NormalStrength;

float PI = acos(-1);


struct PlanetSample
{
    float height;
    float slope;
    float3 normal;
    float temperature;
    float humidity;
};


bool SphereIntersection(float3 rayStart, float3 rayDir, float3 spherePos, float sphereRadius, out float t)
{
    // Vector from sphere center to ray origin
    float3 oc = rayStart - spherePos;

    // Quadratic equation setup
    float a = dot(rayDir, rayDir);
    float b = 2.0 * dot(oc, rayDir);
    float c = dot(oc, oc) - sphereRadius * sphereRadius;

    // Determines whether intersection occurs
    float discriminant = b * b - 4.0 * a * c;

    // Negative means no intersection
    if (discriminant < 0.0)
    {
        t = -1.0;
        return false;
    }

    float sqrtD = sqrt(discriminant);

    // Calculation of intersection distance along ray
    float t1 = (-b - sqrtD) / (2.0 * a);
    float t2 = (-b + sqrtD) / (2.0 * a);

    // Closest intersection
    t = min(t1, t2);

    // Check if intersection is behind ray origin
    if (t < 0.0)
        t = max(t1, t2);

    // Returns true if intersection exists
    return t >= 0.0;
}


// Hash function used for noise generation
float3 hash33(float3 p)
{
    p = float3(
        dot(p,float3(127.1,311.7,74.7)),
        dot(p,float3(269.5,183.3,246.1)),
        dot(p,float3(113.5,271.9,124.6))
    );

    return -1.0 + 2.0 * frac(sin(p) * 43758.5453123);
}


// 3D Gradient noise
float4 GradientNoise3D_Deriv(float3 x)
{
    // Grid creation
    float3 i = floor(x);
    float3 f = frac(x);

    // Quintic interpolant
    float3 u  = f*f*f*(f*(f*6.0 - 15.0) + 10.0);
    float3 du = 30.0*f*f*(f*(f - 2.0) + 1.0);

    // Gradients
    float3 ga = hash33(i + float3(0,0,0));
    float3 gb = hash33(i + float3(1,0,0));
    float3 gc = hash33(i + float3(0,1,0));
    float3 gd = hash33(i + float3(1,1,0));
    float3 ge = hash33(i + float3(0,0,1));
    float3 gf = hash33(i + float3(1,0,1));
    float3 gg = hash33(i + float3(0,1,1));
    float3 gh = hash33(i + float3(1,1,1));

    // Projections
    float va = dot(ga, f - float3(0,0,0));
    float vb = dot(gb, f - float3(1,0,0));
    float vc = dot(gc, f - float3(0,1,0));
    float vd = dot(gd, f - float3(1,1,0));
    float ve = dot(ge, f - float3(0,0,1));
    float vf = dot(gf, f - float3(1,0,1));
    float vg = dot(gg, f - float3(0,1,1));
    float vh = dot(gh, f - float3(1,1,1));

    // Interpolation
    float v =
        va +
        u.x * (vb - va) +
        u.y * (vc - va) +
        u.z * (ve - va) +
        u.x * u.y * (va - vb - vc + vd) +
        u.y * u.z * (va - vc - ve + vg) +
        u.z * u.x * (va - vb - ve + vf) +
        u.x * u.y * u.z * (-va + vb + vc - vd + ve - vf - vg + vh);

    float3 d =
        ga +
        u.x * (gb - ga) +
        u.y * (gc - ga) +
        u.z * (ge - ga) +
        u.x * u.y * (ga - gb - gc + gd) +
        u.y * u.z * (ga - gc - ge + gg) +
        u.z * u.x * (ga - gb - ge + gf) +
        u.x * u.y * u.z * (-ga + gb + gc - gd + ge - gf - gg + gh) +

        du * (
            float3(vb - va, vc - va, ve - va) +
            u.yzx * float3(
                va - vb - vc + vd,
                va - vc - ve + vg,
                va - vb - ve + vf
            ) +
            u.zxy * float3(
                va - vb - ve + vf,
                va - vb - vc + vd,
                va - vc - ve + vg
            ) +
            u.yzx * u.zxy * (-va + vb + vc - vd + ve - vf - vg + vh)
        );

    return float4(v, d);
}


// Fractal Brownian Motion
float4 FbmHeightGradient(float3 p, float frequency, int octaves)
{
    float height = 0.0;
    float3 gradient = 0.0;

    // FBM Parameters
    float H = 1;
    float G = exp2(-H);
    float f = frequency;
    float a = StartAmplitude;

    float maxAmplitude = 0.0;

    // Octaves are summed
    for (int i = 0; i < octaves; i++)
    {
        float4 n = GradientNoise3D_Deriv(f * p);

        height += a * n.x;
        gradient += a * f * n.yzw;

        maxAmplitude += a;

        f *= 2.0;
        a *= G;
    }

    // Height and gradient gets normalized  
    height /= maxAmplitude;
    gradient /= maxAmplitude;

    return float4(0.5 * height + 0.5, 0.5 * gradient);
}


// Domain warping
float4 WarpedHeightGradient(float3 p)
{
    float warpStrength = WarpStrength;
    float warpFrequency = StartFrequency;
    int warpOctaves = 10;

    // Noise is used to distort input position
    float qx = FbmHeightGradient(p + float3(0.0, 0.0, 0.0), warpFrequency, warpOctaves).x;
    float qy = FbmHeightGradient(p + float3(5.2, 1.3, 2.7), warpFrequency, warpOctaves).x;
    float qz = FbmHeightGradient(p + float3(6.5, 1.6, 3.2), warpFrequency, warpOctaves).x;

    // Distortion offset
    float3 q = float3(qx, qy, qz);

    // Final noise sample using distorted coordinates
    return FbmHeightGradient(p + warpStrength * q, StartFrequency, Octaves);
}


// Planet sampler
PlanetSample SamplePlanet(float3 p)
{
    PlanetSample s;

    // Height & Normal
    float4 hg = WarpedHeightGradient(p);

    float3 gradient;

    // Height and gradient extracted from generated noise
    s.height = hg.x;
    gradient = hg.yzw;

    float3 sphereNormal = normalize(p);

    // Projection of the gradient onto the tangent plane of the sphere
    float3 surfaceGradient = gradient - sphereNormal * dot(gradient, sphereNormal);

    float normalStrength = NormalStrength;

    // The surface normal is tilted by the terrain gradient
    s.normal = normalize(sphereNormal - normalStrength * surfaceGradient);


    // Slope
    s.slope = saturate(length(surfaceGradient));


    // Temperature
    // Latutude dependent temperature 
    float latTemperature = sqrt(saturate(1.0 - sphereNormal.y * sphereNormal.y));

    // Noise dependent temperature
    float localTemperature = saturate(FbmHeightGradient(p, StartFrequency, 10).x - s.height);

    // Total temperature
    float temperature = 0.75 * latTemperature + 0.25 * localTemperature;

    s.temperature = temperature;


    return s;
}


// Coloring of the planet
float3 PlanetColor(PlanetSample planet)
{
    // Declaration of colors
    float3 sand = float3(0.75, 0.62, 0.42);
    float3 rock = float3(0.4, 0.34, 0.32);
    float3 snow = float3(0.85, 0.85, 0.82);

    float3 color = sand;

    // Rock mask based on terrain slope
    float rockSlopeMask  = smoothstep(0.5, 1.0, planet.slope);

    // Rock mask based on terrain height
    float rockHeightMask = smoothstep(0.55, 0.65, planet.height);
    float rockMask = saturate(0.3*rockSlopeMask + 0.7*rockHeightMask);

    // Snow mask based on temperature
    float snowColdMask   = 1.0 - smoothstep(0.65, 0.7, planet.temperature);
    float snowMask = saturate(snowColdMask);

    // Final color calculated through successive linear interpolation using their masks
    color = lerp(color, rock, rockMask);
    color = lerp(color, snow, snowMask);

    return saturate(color);
}


// Simple color gradient used when displaying for example temperature
float3 ColorGradient(float value)
{   
    float3 orange = float3(1.0, 0.647, 0.0);
    float3 blue = float3(0.0, 0.0, 1.0);
    
    float3 color = lerp(blue, orange, value);

    return color;
}


[numthreads(8, 8, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= Size.x || id.y >= Size.y)
        return;

    // Pixel coordinates are centered around the middle of the screen
    float2 uv = id.xy - Size * 0.5;

    // Camera right and up directions are calculated from camera forward using cross product
    float3 right = normalize(cross(float3(0,1,0), CameraDir));
    float3 up = normalize(cross(CameraDir, right));

    // Ray direction calculated using camera directions, focal length and centered pixel coordinates
    float3 rayDir = normalize(CameraDir * FocalLength + right * uv.x + up * uv.y);
    float t;

    // Planet surface intersection
    if (SphereIntersection(CameraPos, rayDir, PlanetPos, PlanetRadius, t))
    {   
        // Intersection point calculation
        float3 intersectionPoint = CameraPos + rayDir * t;
        float3 sphereNormal = normalize(intersectionPoint - PlanetPos);

        PlanetSample planet = SamplePlanet(sphereNormal);

        float3 surfaceColor = PlanetColor(planet);
        //float3 surfaceColor = ColorGradient(planet.temperature);

        // Direct light calculation using planet normal and sun direction
        float directLight = saturate(dot(planet.normal, SunDir));

        // Small ambient light
        float ambientLight = 0.01;

        // Surface illumination calculation through sum of direct and ambient light
        float surfaceIllumination = directLight + ambientLight;

        // Pixel color calculation using surface color and surface illumination
        float3 color = surfaceColor * surfaceIllumination;
        Result[id.xy] = float4(color.x, color.y, color.z, 1.0);
        return;
    }

    // Pixel color set to black in case of no intersection
    float4 black = float4(0, 0, 0, 1.0);

    Result[id.xy] = black;
}
